title: Nela Smrzova
description: Blog about testing and stuff

url: http://nelasmrzova.cz
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5

navigation:
 - title: Posts
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: neliczka
   twitter: neliczka
   instagram: neliczka
   #facebook: brianmaierjr
   email: n.nelis.s@gmail.com

#google_analytics: "UA-58263416-1"
